### PR TITLE
Travis script should fail on error

### PR DESCRIPTION
**Pull request by jetersen**
If any doubt: https://explainshell.com/explain?cmd=set+-ex

### CODE REVIEW

**Review by madhead — COMMENTED** [review]
👍

**Comment by jetersen** [comment]
and now it fails because of jenkins's bootstrap core assets is not on jcenter 👍 which is fixed in #60 kek

**Review by madhead — COMMENTED** [review]
👍

**Review by madhead — APPROVED** [review]
👍

**Pull request merged**
