### PR TITLE
Use Jenkins plugin for Kotlin Stdlib

### PR DESCRIPTION
**Pull request by jetersen**
Using the Jenkins plugin version you get a common place to allow Kotlin ClassFilter and you would be able to disable `pluginFirstClassLoader` though you are pulling in a lot of dependencies that not packaged as Jenkins plugin.

Sadly there is still issues with Jenkins's war-for-test trying to be downloaded.

Hopefully I can have the Maven Kotlin plugin parent pom up soon.
Definitely switching back to Maven since Gradle Jpi plugin is not that reliable.

### CODE REVIEW

**Comment by madhead** [comment]
Is that plugin updated for every Kotlin version? I kind of understand that this is related to class serialization issues in newer Jenkinses, but can't it just be solved by listing classes somewhere in `META-INF`?

What's wrong with `pluginFirstClassLoader` why does it need to be disabled?

And what is the issue with war-for-test? This plugin has no tests that need Jenkins context (and I think it's pretty ok).

Thanks!

**Comment by jetersen** [comment]
of course I will do my best to to ensure that the plugin will be update for every Kotlin version going forward 👍
Yes it can be solved by listing classes in the class filter file but it would be better to combine efforts inside one plugin so not everyone trying to do use Kotlin have to remember remember their filter.



[pluginFirstClassLoader](https://jenkinsci.github.io/maven-hpi-plugin/hpi-mojo.html#pluginFirstClassLoader)
> This is useful if the plugins that you want to depend on exposes conflicting versions of the libraries you are using, but enabling this switch makes your code susceptible to classloader constraint violations.

few examples of constraints
https://issues.jenkins-ci.org/browse/JENKINS-42792
https://github.com/openshift/jenkins-plugin/issues/147
https://stackoverflow.com/questions/28318934/classloader-issue-in-custom-jenkins-plugin

The issue about war-for-test is that is no longer included in dependency tree after Jenkins version 2.64 yet the Gradle Jpi Plugin's dependency on jenkins-test-harness:2.0 is trying to retrieve war-for-test
https://github.com/jenkinsci/gradle-jpi-plugin/pull/94#issuecomment-344924735

The issue prevents me from doing a full build using any core higher than 2.64, here is the build log for the branch:
```
:localizer UP-TO-DATE
:kaptGenerateStubsKotlin
:kaptKotlin
w: Note: by.dev.madhead.doktor.classic.DoktorStep.DoktorStepDescriptor indexed under hudson.Extension
w: Note: by.dev.madhead.doktor.config.ConfluenceServer.ConfluenceServerDescriptor indexed under hudson.Extension
w: Note: by.dev.madhead.doktor.config.ConfluenceServers indexed under hudson.Extension
w: Note: by.dev.madhead.doktor.model.DescribableString.DescribableStringDescriptor indexed under hudson.Extension
w: Note: by.dev.madhead.doktor.pipeline.DoktorStep.DoktorStepDescriptor indexed under hudson.Extension
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:compileGroovy NO-SOURCE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:configureManifest
:war
:assemble
:kaptGenerateStubsTestKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kaptGenerateStubsTestKotlin'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not find jenkins-war-war-for-test.jar (org.jenkins-ci.main:jenkins-war:2.102).
     Searched in the following locations:
         https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.102/jenkins-war-2.102-war-for-test.jar
   > Could not find bootstrap-core-assets.jar (org.jenkins-ci.ui:bootstrap:1.3.2).
     Searched in the following locations:
         https://jcenter.bintray.com/org/jenkins-ci/ui/bootstrap/1.3.2/bootstrap-1.3.2-core-assets.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 17s
9 actionable tasks: 5 executed, 4 up-to-date
Could not find jenkins-war-war-for-test.jar (org.jenkins-ci.main:jenkins-war:2.102).
Searched in the following locations:
    https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.102/jenkins-war-2.102-war-for-test.jar
12:33:16: Task execution finished 'build'.
```

To fix this Gradle Hpi has to depend on jenkins-test-harness-2.23 when using Jenkins core above 2.64 because of https://github.com/jenkinsci/jenkins-test-harness/commit/90cae737b68268c2d90fd89cfa267736ad05a8a7#diff-600376dffeb79835ede4a0b285078036

**Comment by madhead** [comment]
Is it possible to overcome that test harness issues by tweaking transitive dependencies in this build?

**Comment by jetersen** [comment]
Yes absolutely, however there is still the problem of the bootstrap-core-assets not being on JCenter so I had to add the Jenkins repo.

So now it builds 👍

**Comment by jetersen** [comment]
A little dishearting that travis actually said it managed to build first commit:
https://travis-ci.org/madhead/doktor/builds/359615898

it clearly failed 😢 
https://travis-ci.org/madhead/doktor/builds/359615898#L1250-L1260
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':kaptGenerateStubsTestKotlin'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not find jenkins-war-war-for-test.jar (org.jenkins-ci.main:jenkins-war:2.102).
     Searched in the following locations:
         https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.102/jenkins-war-2.102-war-for-test.jar
   > Could not find bootstrap-core-assets.jar (org.jenkins-ci.ui:bootstrap:1.3.2).
     Searched in the following locations:
         https://jcenter.bintray.com/org/jenkins-ci/ui/bootstrap/1.3.2/bootstrap-1.3.2-core-assets.jar
```

**Comment by madhead** [comment]
Probably a bug in bash script that ignores failures...

**Comment by madhead** [comment]
That all looks cool at a first glance, but I'll take a more detailed look, probably on the weekend.

Additional thanks for updating all the versions!

My only concern is that now this plugin depends on another one (Kotlin plugin).

**Comment by jetersen** [comment]
Well the Kotlin plugin is only pulling in the the stdlib dependency so it can be managed properly by the Jenkins class loader. And as the added bonus we can combine the classfilter for Kotlin classes there.

**Comment by jetersen** [comment]
Gradle hpi 0.26 should fix the test-harness issue 👍

**Comment by madhead** [comment]
Hello, @casz!

I've decided to just white-list the classes, cause I see no issues with it. Thank's for the version update and JPI plugins stuff, I've tested those changes and they allowd me to check JEP-200 changes.

**Pull request closed without merging**
